# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20171013_1019'),
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sequence'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='verb',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
