# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_auto_20171013_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='sequence',
        ),
    ]
