# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='AnimText',
            fields=[
                ('sequence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Sequence')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            bases=('core.sequence',),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('sequence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Sequence')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            bases=('core.sequence',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('sequence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Sequence')),
                ('url', models.URLField(blank=True, null=True)),
                ('vidfile', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('core.sequence',),
        ),
        migrations.AddField(
            model_name='sequence',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Story'),
        ),
    ]
