# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171107_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['scene']},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([]),
        ),
    ]
