# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171012_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdescription', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question',
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Exercise'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Question'),
        ),
    ]
