# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171012_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='core.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.Exercise'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='core.Story'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='core.Scene'),
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together=set([('story', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([('scene', 'order')]),
        ),
    ]
