# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171013_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='animtext',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animtexts', to='core.Scene'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='core.Scene'),
        ),
        migrations.AddField(
            model_name='video',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.Scene'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='scene',
        ),
    ]
