# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171013_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlank',
            fields=[
                ('sequence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Sequence')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=512)),
                ('multiline', models.BooleanField(default=False)),
                ('answer1', models.CharField(blank=True, max_length=256)),
                ('answer2', models.CharField(blank=True, max_length=256)),
                ('answer3', models.CharField(blank=True, max_length=256)),
            ],
            bases=('core.sequence',),
        ),
        migrations.CreateModel(
            name='MultChoice',
            fields=[
                ('sequence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Sequence')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=512)),
                ('option1', models.CharField(blank=True, max_length=256)),
                ('option2', models.CharField(blank=True, max_length=256)),
                ('option3', models.CharField(blank=True, max_length=256)),
                ('option4', models.CharField(blank=True, max_length=256)),
                ('option5', models.CharField(blank=True, max_length=256)),
                ('option6', models.CharField(blank=True, max_length=256)),
                ('answer', models.CharField(blank=True, max_length=256)),
            ],
            bases=('core.sequence',),
        ),
    ]
