# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 14:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_auto_20171013_1247'),
        ('core', '0005_fillblank_multchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animtext',
            name='sequence_ptr',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sequence_ptr',
        ),
        migrations.RemoveField(
            model_name='fillblank',
            name='sequence_ptr',
        ),
        migrations.RemoveField(
            model_name='multchoice',
            name='sequence_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='video',
            name='sequence_ptr',
        ),
        migrations.AddField(
            model_name='sequence',
            name='events',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=-1),
        ),
        migrations.DeleteModel(
            name='AnimText',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='FillBlank',
        ),
        migrations.DeleteModel(
            name='MultChoice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
