# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 14:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171017_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='events',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
