# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171016_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animtext',
            old_name='scene2',
            new_name='scene',
        ),
    ]
