# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171016_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='video',
            name='scene',
        ),
    ]
