# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0003_remove_experience_sequence'),
        ('core', '0007_auto_20171017_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='scene',
        ),
        migrations.AddField(
            model_name='scene',
            name='events',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
