# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171016_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animtext',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='animtext',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='animtext',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animtext',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sequence',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='core.Scene'),
        ),
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qdescription',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.RemoveField(
            model_name='animtext',
            name='sequence_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='animtext',
            unique_together=set([('scene', 'order')]),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sequence_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set([('scene', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together=set([('scene', 'order')]),
        ),
        migrations.RemoveField(
            model_name='video',
            name='sequence_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([('scene', 'order')]),
        ),
    ]
