# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userintel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintel',
            name='eventnr',
            field=models.IntegerField(default=0),
        ),
    ]
