# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
