# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userintel_eventnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
