# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171104_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scoreMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='scoreReq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='scoreTotal',
            field=models.IntegerField(default=0),
        ),
    ]
