# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171104_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='scoreTotal',
        ),
        migrations.AlterField(
            model_name='score',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='core.Scene'),
        ),
    ]
