# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_story_totalscoremax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='totalScoreMax',
        ),
    ]
